#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 4
#SBATCH --ntasks-per-node 1
#SBATCH --time 00:20:00
#SBATCH --partition=teach_cpu
#SBATCH --account=COSC028844
#SBATCH --output init-test.out
#SBATCH --exclusive 

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
# ./d2q9.gprof input_128x128.params obstacles_128x128.dat
# gprof -l d2q9.gprof gmon.out > profile-vec.txt
# export OMP_NUM_THREADS=28
# OMP_PROC_BIND=close OMP_PLACES=cores ./d2q9-bgk-omp input_128x128.params obstacles_128x128.dat
# OMP_PROC_BIND=close OMP_PLACES=cores ./d2q9-bgk-omp input_256x256.params obstacles_256x256.dat
# OMP_PROC_BIND=close OMP_PLACES=cores ./d2q9-bgk-omp input_1024x1024.params obstacles_1024x1024.dat

# advixe-cl --collect=roofline --project-dir=./advi-ser-1024-v2 ./debug input_1024x1024.params obstacles_1024x1024.dat

# mpirun -np 56 -l ./hello_world
# ./HPC-Assignment1/d2q9-bgk input_128x128.params obstacles_128x128.dat
# ./HPC-Assignment1/d2q9-bgk input_256x256.params obstacles_256x256.dat
# ./HPC-Assignment1/d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

mpirun -np 4 -l ./d2q9-bgk-vectorized input_128x128.params obstacles_128x128.dat
# ./d2q9-bgk-vectorized input_256x256.params obstacles_256x256.dat
# ./d2q9-bgk-vectorized input_1024x1024.params obstacles_1024x1024.dat

# ./d2q9-bgk-optimized input_128x128.params obstacles_128x128.dat
# ./d2q9-bgk-optimized input_256x256.params obstacles_256x256.dat
# ./d2q9-bgk-optimized input_1024x1024.params obstacles_1024x1024.dat

